### ISSUE TITLE
(Edited) Update the troubleshooting page on the wiki to cover errors when installing using Python 2.7.

### ISSUE THREAD

**Issue by Sadasiva20** [oppia/oppia-web-developer-docs#206]
When running the Oppia development server on the linux vm , I am running  into the following error: Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 119, in _get_module_details
    code = loader.get_code(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 281, in get_code
    self.code = compile(source, self.filename, 'exec')
  File "/home/joe/Documents/opensource/oppia/scripts/start.py", line 86
    def alert_on_exit() -> Iterator[None]:
                        ^
SyntaxError: invalid syntax 

Thanks.

**Comment by asxcode** [comment]
@Sadasiva20 you're trying to run it using Python 2.7, use the recommended version for Oppia or follow [installation instructions for Linux](https://github.com/oppia/oppia/wiki/Installing-Oppia-%28Linux%3B-Python-3%29)

**Comment by Sadasiva20** [comment]
Thank you, I have reinstalled Oppia.

**Comment by seanlip** [comment]
Note: Updated the title of this issue to note this on the troubleshooting page of the wiki. Moving it to the wiki repo too.

**Comment by seanlip** [comment]
We no longer use Python 2.7, closing.
