### ISSUE TITLE
[Docker]: Include note regarding FileNotFoundError as expected error in the docker setup

### ISSUE THREAD

**Issue by gp201** [oppia/oppia-web-developer-docs#276]
Add a note in the docker setup page that the below error is expected and is happening since the dev-server container is waiting for the webpack compiler to complete.

```
2024-03-15 20:33:29 ERROR:root:Exception raised: [Errno 2] No such file or directory: 'dist/oppia-angular/index.html'
2024-03-15 20:33:29 Traceback (most recent call last):
2024-03-15 20:33:29   File "/tmp/tmpB9HztM/lib/python3.8/site-packages/webapp2.py", line 604, in dispatch
2024-03-15 20:33:29     return method(*args, **kwargs)
2024-03-15 20:33:29   File "/app/oppia/core/controllers/acl_decorators.py", line 116, in test_can_access
2024-03-15 20:33:29     return handler(self, *args, **kwargs)
2024-03-15 20:33:29   File "/app/oppia/core/controllers/oppia_root.py", line 77, in get
2024-03-15 20:33:29     self.render_template('index.html', template_is_aot_compiled=True)
2024-03-15 20:33:29   File "/app/oppia/core/controllers/base.py", line 696, in render_template
2024-03-15 20:33:29     self.response.write(load_template(
2024-03-15 20:33:29   File "/app/oppia/core/controllers/base.py", line 96, in load_template
2024-03-15 20:33:29     with utils.open_file(filepath, 'r') as f:
2024-03-15 20:33:29   File "/app/oppia/core/utils.py", line 133, in open_file
2024-03-15 20:33:29     open(filename, mode, encoding=encoding, newline=newline)
2024-03-15 20:33:29 FileNotFoundError: [Errno 2] No such file or directory: 'dist/oppia-angular/index.html'
```

**Comment by seanlip** [comment]
Closing, we are no longer planning to support Docker.
